### ISSUE TITLE
CSS Selector :hover doesn't 'unhover' properly

### ISSUE THREAD

**Issue by gtnardy** [ultralight-ux/Ultralight#318]
Here there, when I use the selector `:hover` to apply a background color to an _(img)_ element, it doesn't remove the background color completely when I "unhover" the element:

Here's a video: https://streamable.com/3rv5av

Here's my complete CSS:
```css
#spawn_list {
	margin: 50px;
	background-color: #00000059;
	padding: 10px;
	position: absolute;
	right: 0;
	left: 0;
	bottom: 0;
}

.spawn_item {
	width: 75px;
	height: 75px;
	padding: 2px;
}

.spawn_item:hover {
	background-color: #ff0000;
	cursor: pointer;
}
```

HTML if useful:
```html
<body>
	<div id="spawn_list">
		<img class="spawn_item" src="https://i.imgur.com/sKjbueM.jpg" />
		<img class="spawn_item" src="https://i.imgur.com/OcyUjXp.jpg" />
		<img class="spawn_item" src="https://i.imgur.com/nkPvu96.jpg" />
		<img class="spawn_item" src="https://i.imgur.com/ls0cD9b.jpg" />
		<img class="spawn_item" src="https://i.imgur.com/aClqtmd.jpg" />
	</div>
</body>
```

The problem can be 'circumvented' when forcing the default `background-color` to be some solid color like:

```css
.spawn_item {
	...
	background-color: white;
}
```

But still cannot go back to transparent one.

Can be related: #319
