### ISSUE TITLE
Weird behavior with text-decoration, and opacity on hover

### ISSUE THREAD

**Issue by p0358** [ultralight-ux/Ultralight#469]
Suppose this HTML:
```html
<span class="link">(Browse...)</span>
```
this CSS:
```css
.link {
    text-decoration: underline;
}
.link:hover {
    opacity: 0.75;
}
```
It yields this result:
![image](https://user-images.githubusercontent.com/5182588/219828952-439a7c84-2a13-4540-add9-63115676f15f.png)

When the element is hovered, instead of its opacity just changing, it gets the underline undone, and it visibly stretches towards the bottom as the height of elements is different, but it tries to draw on the same height as with text-decoration!!! (that also makes it blurry)

I think the text-decoration shouldn't get unapplied by hover in the first place...
