### ISSUE TITLE
CSS property scale

### ISSUE THREAD

**Issue by jonatan-kruse** [ultralight-ux/ultralight#481]
I'm having issues with the css property `scale`
when used in the way:
```less
.someText {
    scale: 2 1;
}
```
It has no effect on the element that I want to scale even though it does in a "normal" browser.
